"""Config.py where Constants will be stored"""

"""SCREEN"""
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 700
BACKGROUND_COLOR = (25,140,13)
SCREEN_CENTER = (SCREEN_WIDTH/2, SCREEN_HEIGHT/2)

"""COLOR BUTTON"""
HIT_COLOR = "green"
STAND_COLOR = "gold"
NEXT_COLOR = "red"

"""BUTTON SIZE"""
BUTTON_WIDTH = 100
BUTTON_HEIGHT = 70

"""STATES"""
LIST_STATES = ["menu_state", "game_state"]

"""TEXT COLOR"""
TEXT_COLOR = (255, 255, 255)
TEXT_HIT_COLOR = TEXT_COLOR
TEXT_STAND_COLOR = TEXT_COLOR
TEXT_NEXT_COLOR = TEXT_COLOR

"""TEXT POS"""
TEXT_PLAYER_POINTS_POS = (SCREEN_CENTER[0], SCREEN_CENTER[1] + 80)
TEXT_DEALER_POINTS_POS = (SCREEN_CENTER[0], SCREEN_CENTER[1] - 120)

"""IMAGES"""
CARD_WIDTH = 48
CARD_HEIGHT = 64

"""CHIPS"""
DEFAULT_CHIPS = 100
